- CMakeLists.txt
- tools/apt-packagemap.d/10-packagemap.pm
- tools/apt-packagemap.d/50-libperl.pm
- tools/apt-packagemap.d/50-libruby.pm
- tools/apt-packagemap.d/90-devel.pm
- tools/aptitude
- zypper.spec.cmake
update our aptitude compat layer
to also be a drop-in for apt-get
and to allow the mapping of package-names
> Aptitude updates

- tools/apt-packagemap.d/10-packagemap.pm
- tools/apt-packagemap.d/50-python.pm
- tools/aptitude
- zypper.spec.cmake
add generic python package name mapping
have per-OS packagemaps to allow this to work on Fedora
> Aptitude fedora support

- src/Zypper.cc
Should do what it says on the tin.
> Add -x shorthand for --match-exact per #64

- src/bash-completion.sh
> Fix #83 incomplete bash completion for --type

- doc/zypper.8
- doc/zypper.8.txt
one fix for
https://bugzilla.opensuse.org/show_bug.cgi?id=966760
and a re-rendering with asciidoc
> man page fixes

- tools/aptitude
this broke package-manager detection for bindeps
fixes #98
> aptitude: drop interactive mode and handle --version

- po/de.po
We can't use Weblate for translations in zypper at the moment. I want to add translations and translation bug fixes for the German team.
> bug fixes and translations

- doc/zypper.8.d/option_Repo_Aggregates.txt
- doc/zypper.8.txt
- src/Zypper.cc
- src/repos.cc
- src/repos.h
- src/utils/messages.cc
- src/utils/messages.h
Provide the same set of aggregate options for "removerepo" as for "modifyrepo" in zypper.
> Add consistent repo selection options to rr

- src/callbacks/keyring.h
Handles the new report introduced in libzypp for accepting package signing keys received via gpgkey urls in repo configuration files.
> Support listing gpgkey URLs in repo files (bsc#1088037)

- src/Zypper.cc
This patch auto detects if the target filesystem is read only and if it is a transactional server. Zypper will exit directly and print a error message.
> Detect read only filesystem on system modifying operations (fixes #199)

- src/callbacks/keyring.h
Unites the two reports that asks the users to accept new packaging/repository keys , less code ftw
> Unite askUserToAccept*Key report callback (fixes #196)

- src/subcommand.cc
Iterating over (2,RLIMIT_NOFILE] and attempting to close(2) each fd is
quite expensive for two reasons:
1. It is very unlikely that the process already has RLIMIT_NOFILE file
descriptors open, so many of the close(2) operations were unnecessary.
2. Because this is done *immediately* before an exec it's more expensive
than setting O_CLOEXEC (which is handled in-kernel during execve(2)
and is thus likely cheaper).
On most machines RLIMIT_NOFILE is 1024, so the cost of this is not
noticeable. However, inside containers RLIMIT_NOFILE can be in excess of
1 million -- which results in 1000x more close(2) operations. RPM had a
similar bug in the past, and was fixed [using the same /proc/self/fd
walking trick][1].
[1]: https://github.com/rpm-software-management/rpm/commit/5e6f05cd8dad …
> subcommand: optimise fd-closing when running a subcommand

- CMakeLists.txt
This patch removes optimization from debug builds
> Enable optimization only for Release builds

- doc/zypper.8.txt
- src/CMakeLists.txt
- src/Command.cc
- src/Command.h
- src/Zypper.cc
- src/commands/needs-rebooting.cc
- src/commands/needs-rebooting.h
Adds a new command that checks if the reboot hint flag was set in the system.
> Add zypper needs-restarting command (fate#326451)

- doc/zypper.8.txt
- src/commands/inrverify.cc
- zypper.spec.cmake
Actually just updating the `zypper inr` docs.
> Ma fate#325513 resolver namespaces

- src/Config.cc
- src/global-settings.cc
- src/global-settings.h
- zypper.conf
`zypper.conf` option to change the global default.
> zypper.conf: [commit] autoAgreeWithLicenses {=false} (fixes #220)

- src/Command.cc
- src/Command.h
- src/PackageArgs.cc
- src/PackageArgs.h
- src/Zypper.cc
- src/Zypper.h
- src/commands/basecommand.cc
- src/commands/basecommand.h
- src/commands/help.cc
- src/commands/help.h
- src/commands/shell.cc
- src/commands/subcommand.cc
- src/utils/flags/exceptions.cc
- src/utils/flags/zyppflags.cc
- src/utils/flags/zyppflags.h
This PR unifies and simplifies the zypper application flow. All commands are now handled the same way. Even subcommands and zypper shell.
> Simplify the zypper application flow

- src/utils/Augeas.cc
- src/utils/Augeas.h
- src/utils/zypper.aug
- zypper.spec.cmake
Added a bunch of augeas wrapper classes to inspect/manip the tree. Reworked the lense to ease storing values. Actual ability to store values will become a separate PR.
> Rework Augeas class and lense.

- src/Config.cc
- src/Config.h
- src/commands/search/search-packages-hinthack.cc
- src/output/Out.h
- src/output/OutNormal.cc
- src/utils/Augeas.cc
- src/utils/Augeas.h
- src/utils/prompt.cc
- src/utils/prompt.h
Enhancements on the Augeas class to allow option writing. Also Enhancements to the prompt classes to support arbitrary translated words (not just single chars) as prompt reply (and not just 'yes/no').
> fate#325599 config writing and the 'yes/no/always/never' prompt

- zypper.spec.cmake
Adding the missing requires for libaugeas0
> Add Requires: libaugeas0 >= 1.10.0

- src/callbacks/rpm.h
[bsc#1131113](https://bugzilla.opensuse.org/show_bug.cgi?id=1131113)
> Re-show progress bar after pressing retry upon install error

- src/solve-commit.cc
__Delay merge until translations become available.__
> Rephrased `zypper ps` hint (bsc#859480)

- src/misc.cc
[bsc#1145554](https://bugzilla.opensuse.org/show_bug.cgi?id=1145554)
> Ask only once if multiple packages share the same license text 

- doc/zypper.8.d/option_Solver_Flags_Common.txt
- doc/zypper.8.txt
- src/commands/solveroptionset.cc
- src/commands/solveroptionset.h
- src/global-settings.h
- src/solve-commit.cc
[bsc#1146415](https://bugzilla.suse.com/show_bug.cgi?id=1146415), continues openSUSE/libzypp#185.
Add '--solver-focus' option and docs.
> Set resolver focus

- doc/zypper.8.txt
- src/commands/listupdates.h
Since the update command supports tweaking the solver via CLI options
the list-updates command should allow the same (bsc#1153351)
> Add extended solver options to list-updates

- tools/zypper-log
Bug: https://bugzilla.suse.com/show_bug.cgi?id=1156158
> Port zypper-log to python3

- tools/zypper-log
- zypper.spec.cmake
(fixes#304, fixes#306, [bsc#1156158](https://bugzilla.suse.com/show_bug.cgi?id=1156158))
> zypper-log: Replace python by a bash script

- doc/zypper.8.txt
- src/CMakeLists.txt
- src/Command.cc
- src/Command.h
- src/commands/utils.h
- src/commands/utils/purge-kernels.cc
- src/commands/utils/purge-kernels.h
- tests/Locales_test.cc
- tests/PackageArgs_test.cc
- tests/SolverRequester_test.cc
- tests/ZyppFlags_test.cc
- tests/lib/TestSetup.h
- tests/lib/testrepos.py
- zypper.spec.cmake
Adds a new zypper command to cleanup all obsolete kernels as configured by the user.
> Purge kernels

- doc/zypper.8.txt
- src/commands/search/search.cc
- src/info.cc
- src/locales.cc
- src/search.cc
- src/search.h
- src/update.cc
- src/utils/misc.cc
- src/utils/misc.h
Complete for all tables (se/packages/patches/patterns/product).
Man-page and non-table output (info) follows.
> Tag 'R'etracted items in search tabes status columns (jsc#SLE-8770)

- src/Command.cc
- src/Command.h
- src/commands/nullcommands.cc
- src/commands/nullcommands.h
- src/commands/search/search.cc
- src/commands/search/search.h
- tests/Locales_test.cc
- tests/PackageArgs_test.cc
- tests/SolverRequester_test.cc
- tests/utils/text_test.cc
RugPatchSearch and a few more unused ZypperCommand vars.
> Remove undocumented rug legacy features

- src/commands/listpatches.cc
fix help command for list-patches
> Update listpatches.cc fix help command for list-patches

- doc/zypper.8.d/option_Solver_Flags_Common.txt
- doc/zypper.8.txt
- src/Summary.cc
- src/commands/needs-rebooting.cc
- src/update.h
One minor issue fixed in each commit...
> Misc fixes

- doc/zypper.8.txt
- src/commands/locks/add.cc
- zypper.spec.cmake
> doc and manpage

- doc/zypper.8.txt
- src/commands/locks/add.cc
- src/commands/locks/add.h
- src/commands/locks/common.cc
- src/commands/locks/common.h
- src/commands/locks/list.cc
- src/commands/locks/remove.cc
fix https://github.com/openSUSE/zypper/issues/388
> Add comment option for lock command

- src/CMakeLists.txt
- src/CommitSummary.cc
- src/CommitSummary.h
- src/callbacks/rpm.h
- src/commands/distupgrade.cc
- src/commands/inrverify.cc
- src/commands/installremove.cc
- src/commands/patch.cc
- src/commands/sourceinstall.cc
- src/commands/update.cc
- src/commands/utils/purge-kernels.cc
- src/locales.cc
- src/solve-commit.cc
- src/solve-commit.h
The zypper part of the new singletransaction commit strategy.
> Support new reports for singletrans rpm commit

- src/main.cc
[bsc#1186602](https://bugzilla.suse.com/show_bug.cgi?id=1186602).
> Avoid calling 'su' to detect a too restrictive sudo user umask

- doc/zypper.8.d/option_Solver_Flags_Common.txt
- src/Summary.cc
[bsc#1213557](https://bugzilla.suse.com/show_bug.cgi?id=1213557)
> Better explanation of --force-resolution

- src/commands/query/info.cc
- src/info.cc
Hi, I'm doing some code stuff for Hacktoberfest and I figured I'd start off with this.
I am not sure how to go about this, but I kind of know C++.
I think this is one approach of getting Zypper to return exit code 104 if something isn't found in the `zypper info` command.
Let me know what else I need to do.
> Fix issue #504

- src/Summary.cc
- src/Summary.h
- src/info.cc
- zypper.spec.cmake
> New vendor support option flag vendor support superseded

- doc/zypper.8.txt
- src/commands/distupgrade.cc
- src/global-settings.h
- src/solve-commit.cc
[bsc#1221525](https://bugzilla.suse.com/show_bug.cgi?id=1221525)
> New option --remove-orphaned to remove all orphaned packages in dup.

- src/Zypper.cc
[bsc#1223766](https://bugzilla.suse.com/show_bug.cgi?id=1223766)
> Delay zypp lock until command options are parsed

- doc/zypper.8.txt
- src/commands/query/packages.cc
- src/search.cc
- src/search.h
- src/utils/misc.cc
[bsc#1222971](https://bugzilla.suse.com/show_bug.cgi?id=1222971)
> Add zypper pa --system

- doc/zypper.8.txt
- src/commands/repos/list.cc
- src/commands/reposerviceoptionsets.cc
- src/commands/reposerviceoptionsets.h
- zypper.conf
- zypper.spec.cmake
[bsc#1232458](https://bugzilla.suse.com/show_bug.cgi?id=1232458)
> Show keep-packages in lr

- src/commands/basecommand.cc
- zypper.spec.cmake
Complements openSUSE/libzypp#624
> fix context of repo variable evaluation

- src/commands/repos/add.cc
- src/commands/services/add.cc
- src/repos.cc
- src/repos.h
- zypper.spec.cmake
[bsc#1246466](https://bugzilla.suse.com/show_bug.cgi?id=1246466)
> Fix addrepo to handle explicit --check and --no-check requests
