- src/utils/ansi.h
https://bugzilla.opensuse.org/show_bug.cgi?id=925678
reported that in non-terminal cases ANSI color-codes
were left out, but color-reset codes still appeared
> only use ANSI codes on terminals (bnc#925678)

- src/bash-completion.sh
https://bugzilla.opensuse.org/show_bug.cgi?id=928650
> add bash completion for install+remove+update commands (bnc#928650)

- CMakeLists.txt
- tools/apt-get
- zypper.spec.cmake
using a symlink
This allows more Debian CLI examples to be used verbatim.
> add apt-get alias for aptitude

- src/Zypper.cc
- src/repos.cc
- refactor priority parsing into parse_priority()
- add priority to addrepo for both by repo file and url cases
I have desired this feature for quite a while, since it seems the only proper way to add repositories is with a priority, but that requires adding then modifying. That makes documentation on how to add a repo cumbersome in addition to usage.
This has been discussed on mailing list a few times including http://lists.opensuse.org/opensuse-factory/2015-07/msg00377.html thread.
Semi-related it seem like a good idea for repositories on obs to include a priority in their `.repo` file relevant to their intended usage. Most likely this would be best done with string priorities as suggested in the todo in `repos.cc`. I may implement that next after this pull request has been accepted.
> Provide priority option on addrepo command.

- po/createPot
Commit 855ef47 changed \_PL into PL\_ everywhere but here (po/createPot script).
We need to change \_PL into PL\_ here too in order to produce a pot file with plural forms again.
> [createPot] Fix plural form detection

- src/RequestFeedback.cc
Add "-t patch" for optional patch in the warning message. If the user follow the current warning, he will get something like: 
- sudo zypper in openSUSE-2016-1409-1
Loading repository data...
Reading installed packages...
'openSUSE-2016-1409-1' not found in package names. Trying capabilities.
No provider of 'openSUSE-2016-1409-1' found.
Proper way to install this patch:
- sudo zypper in patch:openSUSE-2016-1409-1
~~- sudo zypper in -t patch openSUSE-2016-1409-1~~
> Add "-t patch" for optional patch

- tests/lib/CMakeLists.txt
The tests fail to build and run on Fedora and OpenSUSE without the library name being fixed, since `libboost_thread-mt.so` doesn't exist anymore.
> tests/lib: Fix name of boost_thread library being linked

- tools/aptitude
https://bugzilla.opensuse.org/show_bug.cgi?id=1028119
puppet-agent expects apt-get -s upgrade to be non-interactive
> aptitude: simulate is non-interactive (boo#1028119)

- CMakeLists.txt
- package/zypper.changes
- tools/apt
- tools/aptitude
- zypper.spec.cmake
newer Debian versions use 'apt' as their preferred package management
tool - using mostly the same CLI as previous apt-get and aptitude.
Note: not tested
> Add Debian apt compat

- src/repos.cc
Zypper wrongfully returns a error for "zypper clean -a" when there are no repositories registered to the system.
> Check if nr enabled of repositories is > 0 before giving error (bsc#1089504)

- src/Zypper.cc
This disables the refresh of system repositories when --installed-only is passed. There is no need to refresh them in that case.
> Disable repository operations when searching installed packages (bsc#1084525)

- src/Zypper.cc
- src/search.cc
- src/search.h
See [Bug 907538](https://bugzilla.opensuse.org/show_bug.cgi?id=907538) - zypper shell search parsing minus (and duplicates).
The  desired behavior is to use the match-mode provided as CLI arg. If no match mode is explicitly requested, we use globbing if an argument contains globbing chars, regex if the pattern is enclosed in '/'es, else substring.
A name-argument containing one or 2 '-'es ("n-v" or "n-v-r"), should also match a package with this name and version (exact match!), i.e. the same as `se -x 'n = v'` or `se -x 'n = v-r '`.
Additionally a detailed search result (-s) must not list items without a match, like it did
$ zypper se -sx 'libzypp = 17.1.1'
S | Name    | Type    | Version    | Arch   | Repository       
--+---------+---------+------------+--------+------------------
i | …
> Ma broken search

- doc/zypper.8.txt
- src/Zypper.cc
- src/info.cc
Teaches zypper info and zypper search about supplements.
> Add --supplements switch to search and info (fixes #184)

- src/utils/text.h
- tests/utils/text_test.cc
Fix one possible and one definitive out of bounds read in MbsIterator:
Out of bounds read happens in that case:
-> previous read reads last char 
-> current read advances pos and sets _trest to 0 
-> mbrtowc will return error -2 ( because max read bytes is 0 ? )
-> we enter if ( _tread >= (size_t)-2 ) 
-> sets _tread to 1 
-> while loop will continue behind the last char with _tpos+_tread
Also added a testcase that triggers that behaviour by setting up a teststring that has 
multibyte continuation characters after a \0.
> Out of bounds read in mbs iterator

- src/repos.cc
Zypper should return a error if unknown repositories are passed to lr and ref, currenty it returns 0. 
This patches fixes the behaviour.
> Set error status if repositories passed to lr and ref are not known (BSC #1093103)

- src/Table.h
- src/Zypper.cc
- src/repos.cc
- src/search.cc
- zypper.spec.cmake
This patch allows us to sort a table by multiple columns and a per row user value
> Sort search results by multiple columns (bsc#1066215)

- doc/zypper.8.d/option_Solver_Flags_Installs.txt
- doc/zypper.8.txt
- src/Zypper.cc
- src/solve-commit.cc
- src/solve-commit.h
This patch adds the same set of expert switches to all zypper commands that could install packages as they are available for zypper dup:
--allow-downgrade
--no-allow-downgrade
--allow-name-change
--no-allow-name-change
--allow-arch-change
--no-allow-arch-change
--allow-vendor-change
--no-allow-vendor-change
> Add expert (allow-*) options to zypper in (bsc#428822)

- src/ZCOMMAND.h
- src/Zypper.cc
- src/Zypper.h
- src/configtest.h
- src/download.h
- src/locks.h
- src/ps.h
- src/solve-commit.cc
- src/solve-commit.h
- src/source-download.h
- src/subcommand.h
Allow commonly used option sets to be mixed into several command optrions.
> Add MixinOptions template to combine multiple common option sets.

- src/Zypper.cc
Currently zypper verify and source-install do not check for root privs and fails due to rpm return with error because it can not change the rpm datbse, this patches adds the checks so the user experience is more clean.
> Check for root privileges in zypper verify and si (bsc#1066215)

- src/PackageArgs.cc
This fixes a bug in the PackageArgs parser code, which would fail parsing a package argument with a repo prefix that contains multiple colons:
For example:
openSUSE:repo-oss:package    where openeSUSE:repo-oss is the repo alias.
> Handle repo aliases containing multiple ':' in the PackageArgs parser (bsc #1041178)

- src/repos.cc
The previous fix did not cover the case when only a unknown repository was passed to zypper ref. I changed the code so that if there is any unknown repository passed error status will be set.
> Always set error status if any nr of unknown repositories are passed to lr and ref (BSC #1093103)

- src/subcommand.cc
There was a trivial build failure in ca1a44bad47f ("subcommand: optimise
fd-closing when running a subcommand"). Fix that.
Fixes #209.
Signed-off-by: Aleksa Sarai <asarai@suse.de>
> subcommand: fix build failure

- tools/zypper-log
As part of the effort to cull Python 2 dependencies in Fedora, this code was trivially ported to Python 3 to remove the Python 2 dependency in Zypper.
Reference: https://fedoraproject.org/wiki/FinalizingFedoraSwitchtoPython3
Reference: https://fedoraproject.org/wiki/Changes/Mass_Python_2_Package_Removal
> zypper-log: Make Python 3 compatible

- src/repos.cc
In https://bugzilla.opensuse.org/show_bug.cgi?id=1111319 it was discovered that the `--no-cd` option did not work as expected: Even when all repositories were optical repositories it would still try to do something.
The condition https://github.com/openSUSE/zypper/blob/26d146ccdad0845053f1849b79177c7da876635a/src/repos.cc#L801 is missing an else clause, thus incrementing the iterator a second time in https://github.com/openSUSE/zypper/blob/26d146ccdad0845053f1849b79177c7da876635a/src/repos.cc#L808 The result are random non-deactivated repositories (with an odd number of repositories the incrementor would start at the beginning again).
Also fixes a potential segmentation fault when using `--no-cd` and `--no-remote` at the same time.
> Don't iterate twice on --no-cd

- src/Zypper.cc
- src/commands/basecommand.cc
- src/commands/basecommand.h
This patch adds a way to retrieve the list of raw arguments and positional arguments at command execution time.
> Store raw arguments inside BaseCommand if required

- src/utils/flags/flagtypes.cc
- src/utils/flags/flagtypes.h
- src/utils/flags/zyppflags.cc
- src/utils/flags/zyppflags.h
- tests/CMakeLists.txt
- tests/ZyppFlags_test.cc
This patch introduces dependencies between flags, additionally each flag can have its own policy to force a even stricter parsing order.
Also adds the possibility to have pre and post hooks that are called before and after writing a flag.
> Allow more complex argument parsing in zypper

- src/commands/patch.cc
L103 `srOpts.skip_optional_patches=` appears to be superfluous. The option is already set in L93.
I checked the SLE12 code, where L101 `mark_updates_by_issue` created their private `sropts`, but they initialized it the same way. I.e. L100 `if` and  `else` used the same `sropts`, so L93 should be the right place.
> remove superfluous code

- src/CMakeLists.txt
- src/commands/locks/add.cc
- src/commands/locks/common.cc
- src/commands/locks/common.h
- src/commands/locks/list.cc
- src/commands/locks/remove.cc
[ L3-Question: zypper locks display is broken](https://bugzilla.suse.com/show_bug.cgi?id=1112911).
```
type: package
match_type: glob
case_sensitive: on
solvable_name: a*
version: == 1
type: package
match_type: glob
case_sensitive: on
solvable_name: a* == 1
type: package
match_type: glob
case_sensitive: on
complex: AttrMatchData solvable:name a* C SolvableRange\ ==\ 1\ \"\"
```
What a mess. Real life `locks` files may contain the above 3 forms of versioned locks.
The 1st is the one zypper is actually able to handle in `list locks`.
The 2nd one is what zypper creates when creating a versioned lock. Unfortunately this query does not make any sense until libzypp reads it back from the file and translates it into a complex query (3rd). Side effect: You can't remove versioned lock 2nd and 3rd …
> Ma l3 locks

- src/RequestFeedback.cc
When the newest package candidate is from a different vendor,
the current message to the user doesn't clarify which vendors
are involved. Adding the vendor names to the message makes
it easier for the user to decide what to do.
> Clearer message when candidate is from different vendor

- src/Config.cc
Fixes bug https://bugzilla.opensuse.org/show_bug.cgi?id=1122062
Command parsing was broken due to wrong argument flags. The error message is misleading here, because the parser did not get the information that a arg is required, it will ignore the passed argument and not pass it to the argument handler, treating it as positional arg instead. However the handler expects a argument, correctly throwing a error out with the given message.
> Fixed broken argument parsing for --reposd-dir (bsc#1122062)

- src/SolverRequester.cc
- src/misc.cc
- zypper.spec.cmake
([bsc#1113296](https://bugzilla.suse.com/show_bug.cgi?id=1113296)) 
Minimal change which should only affect partially locked packages (only individual versions are locked).
The important fix is to test `ui::asSelectable()(pi)->hasLocks()` to file a solver request. The solver request makes sure existing locks are not accidentally overwritten. The original test for `->locked()` (*all installed* or *all availabe* items are locked) did not include partially locked items.
The remaining code just tries to use the *best unlocked* version, in case the best version is locked (which implies a package is partially locked).
> Improve handling of partially locked packages (bsc#1113296)

- src/commands/search/search.cc
zypper search returned inconsistent results:
while `se -t package kernel-default` correctly listed only package,
the query `se package:kernel-default` also included srcpackages.
> Fix inconsistent results for search (bsc#1119873)

- src/commands/installremove.cc
- src/commands/optionsets.cc
- src/commands/optionsets.h
- src/commands/sourceinstall.cc
- src/commands/sourceinstall.h
- src/misc.cc
- src/misc.h
- src/repos.cc
- src/repos.h
- src/utils/flags/zyppflags.h
This patch adds:
- Download and solver related switches to source-install.
- Enables si to install local rpm files
> Extend zypper source-install (fixes bsc#663358)

- src/Zypper.cc
- src/commands/commonflags.h
- src/commands/installremove.cc
- src/commands/installremove.h
- src/commands/patch.cc
- src/commands/patch.h
- src/commands/query/info.cc
- src/commands/update.cc
- src/commands/update.h
- Fix broken --replacefiles switch (fixes bsc#1123137)
- Catch ZyppFlagsException from global option parsing
- Remove unnecessary use of report_a_bug
> Bugsquashing

- src/commands/needs-rebooting.cc
- src/commands/needs-rebooting.h
- src/solve-commit.cc
Commit should not print a message if 'no reboot is needed'.
> Ma commit reboothint iff true

- doc/zypper.8.txt
- src/CMakeLists.txt
- src/Command.cc
- src/Command.h
- src/commands/basecommand.cc
- src/commands/basecommand.h
- src/commands/commandhelpformatter.h
- src/commands/locale/addlocalecmd.cc
- src/commands/locale/addlocalecmd.h
- src/commands/locale/localescmd.cc
- src/commands/locale/localescmd.h
- src/commands/locale/removelocalecmd.cc
- src/commands/locale/removelocalecmd.h
- src/locales.cc
- src/locales.h
- tests/CMakeLists.txt
- tests/Locales_test.cc
Rebased the original PR #27 on top of current master, this adds support to enable/disable languages that are used to decide which translation packages are installed.
> Adds support to enable/disable language support in zypper

- src/output/Out.cc
This patch changes the behaviour of zypper to suppress exception
history in some cases. We did agree that it is better so see as
much information about the error as possible.
> Always show exception history

- zypper.spec.cmake
This makes it so that dnf-utils and zypper can coexist on an
openSUSE system, which is important when dnf-utils is being used
on openSUSE with tools like Mock.
> Move needs-restarting command to subpackage

- src/CMakeLists.txt
- src/Guardians.h
- src/Zypper.h
- src/callbacks/media.h
Basically fix `Zypper::immediateExitCheck` to repond to the 1st  Ctrl-C.
The media callbacks however have code to handle this exit request, even resetting the exit request depending on the users answer. Not sure if this code is still active, nevertheless allow these callback classes to protect against exiting to the 1st  Ctrl-C.
> Ma faster ctrl c response

- package/zypper.changes
- zypper.spec.cmake
same issue as libzypp#165, with CMake>=3.14, EXCLUDE_FROM_ALL now spreads from
directories to targets.
'make -C tests' does nothing because add_subdirectories(tests) uses the
EXCLUDE_FROM_ALL parameter when ENABLE_BUILD_TESTS is false.
> Fix the package build failure with CMake 3.14

- src/commands/installremove.cc
- src/commands/installremove.h
Fixes a regression in zypper install, which previously only stopped
on a unknown package argument when running in non-interactive mode.
This behaviour was broken when migrating the install command to
the new unified command object API, see commit f2e0f8638a32225ff084458a536eedc0f08ee549.
> Fix unknown package handling in zypper install (fixes bsc#1127608)

- src/repos.cc
The actual fix is the `if` in L875 (2nd commit). The 1st commit just unifies almost duplicate code in the rott/non-root case.
> bsc#1134226 --root refresh does not return 106-ZYPPER_EXIT_INF_REPOS_SKIPPED 

- src/callbacks/keyring.h
- src/callbacks/media.cc
- src/solve-commit.cc
- src/utils/prompt.cc
This patch adds a new option to the prompt generated in the
show_problem() function to show all available conflict information
to a specific solving problem.
Also cleans up the option handling a bit and adds help text.
Needs to land after: https://github.com/openSUSE/libzypp/pull/164
> Add option to show more conflict information

- src/Command.cc
Was there a reason to hide it? That's unconvenient as also no TAB-completion works.
> Unhide 'ps' command in help

- doc/zypper.8.txt
- src/callbacks/rpm.h
- src/commands/optionsets.cc
Libzypp may trigger the file conflict check on --dry-run. Shortened the
summary to report just the number of packages skipped because they are
not yet downloaded.
Adjusted the man-page to point to using '--dry-run --download-only' to get
the full file conflict check without actually installing packages.
> Rephrase file conflict check summary (bsc#1140039)

- src/commands/services/modify.cc
- src/repos.cc
Fix inappropriate use of `schemeIsDownloading` to determine remote repos.
`SchemeIsDownloading` is just a subset of `schemeIsRemote`. Nfs, smb e.g.
are not downloading but remote.
For commands accepting `--medium-type/local/remote` use `schemeIsLocal/IsRemote`
because undecidable types (`plugin://`) can be in/excluded via `--medium-type`.
For the global `--no-remote` prefer `!schemeIsLocal` because `plugin://` usually
resolves to a remote url.
> Fix local/remote url classification.

- src/commands/installremove.cc
Removes a restriction that hardcodes package lookup to use name only if the --force switch was used in remove or install commands. fixes(#289)
> Allow selection by capability if --force switch is used

- doc/zypper.8.txt
- src/commands/utils/download.cc
- src/commands/utils/download.h
Introduces the --repo switch to the zypper download command so
downloading can be limited to a specific repository (jira#SLE-9171)
> Add --repo switch to download

- doc/zypper.8.txt
- src/commands/search/search.cc
- src/commands/search/search.h
- src/search.cc
- src/search.h
- zypper.spec.cmake
This patch adds a new set of switches to zypper to support searching
reverse dependencies for a package or a set of packages (fixes #214)
> Provide reverse-requires search in zypper

- src/SolverRequester.h
- src/commands/selectpatchoptionset.cc
- src/issue.cc
- src/issue.h
- src/output/xmlout.rnc
- src/update.cc
- src/utils/flags/flagtypes.cc
- src/utils/flags/zyppflags.cc
[bsc#1154805](https://bugzilla.suse.com/show_bug.cgi?id=1154805)
Reorganized parts of the xml wtiting code and added issue data to patches. 
Rewrote list_patches_by_issue to orevent duplicate entires (obsoletes the CLI conflict between issue options) and added XML output.
> zypper enhancements for patch issue checking

- src/CMakeLists.txt
- src/commands/basecommand.cc
- src/commands/basecommand.h
- src/utils/MultiParText.h
We prefer translated description paragraphs to contain no
format information (parindent,parsep,NL). MultiParText joins
multiple paragraphs passed to the ctor so they are rendered
correctly.
> basecommand: Allow to add multiple paragraphs as command description

- zypper.spec.cmake
supplementing zypper means zypper-aptitude gets installed by default
and pulls in perl. Neither is desired on small systems.
> zypper-aptitude: don't supplement zypper

- CMakeLists.txt
- src/Config.cc
- src/utils/flags/zyppflags.cc
- src/utils/flags/zyppflags.h
- src/utils/messages.cc
- src/utils/messages.h
- tests/ZyppFlags_test.cc
- zypper.spec.cmake
[bsc#1164543](https://bugzilla.suse.com/1164543)
[bsc#1165573](https://bugzilla.suse.com/1165573)
Includes and fixes #326 
On 15.0/15.1 just issue a warning if abbrev. switches are used.
> Correctly detect ambigous switch abbrev / Still allow legacy longopt abbrev on 15.0/15.1

- doc/zypper.8.txt
- src/Table.cc
- src/Table.h
- src/commands/search/search.cc
- src/search.cc
- src/update.cc
- src/utils/misc.cc
- src/utils/misc.h
Introduces a ´Since´ column showing the date the patch changed to it's current ´Status´. As those data need to be derived from the history file (since libyzpp-17.23.0) and are not available on older systems, the column is suppressed if the history file contains not a single patch-status-change entry.
> Show patch status changes (jsc#sle 5116)

- tests/lib/TestSetup.h
- zypper.spec.cmake
Switches TestSetup to use the new libzypp testcase API 
TODO: bump libzypp version in build requires
> Use new testcase API in libzypp

- tools/apt-packagemap.d/10-packagemap.pm
Extend apt-packagemap
based on the apt line in
https://docs.yoctoproject.org/brief-yoctoprojectqs/index.html
debianutils does not have a proper equivalent for
run-parts
tempfile
installkernel
ischroot
savelog
add-shell
remove-shell
> Extend apt packagemap

- src/commands/repos/add.cc
- src/utils/misc.cc
- src/utils/misc.h
[bsc#1153687](https://bugzilla.suse.com/show_bug.cgi?id=1153687)
This fixes the guessed platform for "obs://<project>/" URLs.
> Quickfix setting "openSUSE_Tumbleweed" as default platform for "MicroOs"

- src/Summary.cc
- src/Summary.h
- src/commands/patch.cc
- src/solve-commit.cc
[bsc#1183268](https://bugzilla.suse.com/show_bug.cgi?id=1183268)
> patch: Let patch reboot-needed flag overrule included packages 

- src/CommitSummary.cc
- src/Config.cc
- src/Zypper.cc
- src/Zypper.h
- src/callbacks/job.h
- src/callbacks/rpm.h
- src/main.cc
- src/output/Out.cc
- src/output/Out.h
- src/output/OutNormal.cc
- src/output/OutNormal.h
- src/output/OutXML.cc
- src/output/OutXML.h
- zypper.spec.cmake
Rpm script output in all modes should now become immediately visible. In singletrans mode non-fatal erros (like failing %post script) will be properly indicated by the progressbars and also provide the correct exit code (107 - ZYPPER_EXIT_INF_RPM_SCRIPT_FAILED).
> Some enhancements around reporting (traditional rpm and singletrans)

- po/de.po
Remove errorneous t in German translation.
Yesterday, I switched to GeckoLinux ROLLING Mate and configured it for German locale.
Today, I noticed a small error in the help output of zypper and looked into submitting a patch.
I took a look at https://en.opensuse.org/openSUSE:Zypper_development but couldn't find a `trunk` branch.
According to https://github.com/openSUSE/zypper/pulls PRs seem to be opened against `master`, so I hope this is correct.
Looking at https://github.com/openSUSE/zypper/commits/master I can see something about Weblate used for translations, but I wasn't able to discover an URL, so please point me to it in case that's used instead.
Tagging @skriesch as she is the last one listed in `de.po` as localisation team. (as of https://github.com/openSUSE/zypper/pull/103 ?)
> Translation Typo

- src/commands/utils/download.cc
This commit changes `zypper-download` such that it behaves more consistent to
`zypper-install` when an argument can't be resolved.
When an argument provided to `zypper-install` can't be resolved to a package, it
prints an error message and exits with `ZYPPER_EXIT_INF_CAP_NOT_FOUND` after
trying to install the remaining packages. In contrast, when `zypper-download`
fails to resolve a package name, it prints a warning, downloads the remaining
packages and exits with `ZYPPER_EXIT_OK`. This behaviour is inconsistent and
makes it unneccessarily difficult to determine, whether all requested packages
have been downloaded by `zypper-download`, e.g., in automation scenarios.
With this change, `zypper-download` now returns `ZYPPER_EXIT_INF_CAP_NOT_FOUND`
instead of `ZYPPER_EXIT_OK` if any argument …
> zypper-download: Handle unresolvable arguments as error

- doc/zypper.8.txt
- src/commands/services/add.cc
- zypper.spec.cmake
[bsc#1203715](https://bugzilla.opensuse.org/show_bug.cgi?id=1203715)
(Plus the man page update for `.no_auto_prune`)
> Zypper serviceadd fails on idempotency check

- src/CMakeLists.txt
- src/Zypper.h
- src/callbacks/media.h
- src/callbacks/repo.h
- src/commands/utils/download.cc
- src/commands/utils/source-download.cc
- src/output/Out.cc
- src/output/Out.h
- src/output/OutNormal.cc
- src/solve-commit.cc
- src/utils/Offering.h
- src/utils/colors.h
Best read IMO commit by commit.
Depending on openSUSE/libzypp#432 we drop any download report frequency limitation (~1 report/sec.) and report whatever libzypp delivers (between 0.1 and 1 report/sec.)
Also a lot of cleanup and coloring the download progress bar.
Still missing: the indication of download retries, but this won't affect the commits here so far.
> Progressbar fixes

- src/Zypper.cc
- src/Zypper.h
- src/main.cc
- src/utils/prompt.cc
This patch updates the SIGINT handling strategy to be signal safe. Meaning the signal handler will do not much more than setting a flag, which we are going to check in the normal program flow as much as possible.
> Improve the SIGC handler to be signal safe ( bsc#1214292 )

- src/bash-completion.sh
If
```shell
alias grep='grep -n'
```
is set before zypper's programmable completion script is sourced, the latter malfunctions. For instance, typing `zypper remove ` and then pressing <kbd>TAB</kbd><kbd>TAB</kbd><kbd>y</kbd><kbd>q</kbd> results in the following.
```console
$ zypper remove 
Display all 2075 possibilities? (y or n)
1000\:libpaper                                    1935\:xfwm4-lang
1001\:libpaper-tools                              1936\:xhost
1002\:libpaper2                                   1937\:xiccd
1003\:libparted-fs-resize0                        1938\:xinit
1004\:libparted2                                  1939\:xkbcomp
1005\:libpathplan4                                193\:farstream-data
1006\:libpci3                                     1940\:xkeyboard-config …
```
> Prefer unaliased `grep` to avoid unexpected/wrong completions.

- CMakeLists.txt
On multi-arch distributions such as Debian or Ubuntu we need to check a different path in case ZYPP_PREFIX is not set.
Fixes https://github.com/openSUSE/zypper/issues/52
> Find ZyppCommon on multi-arch systems without having to set ZYPP_PREFIX

- src/bash-completion.sh
- src/commands/services/list.cc
Bash completion failed if numbers in the 1st column are right-adjusted.
On the fly fixed `ls` to use the same adjustment as `lr` (right-adjusted)
> bash completion lr vs ls fix

- doc/zypper.8.txt
- src/Summary.cc
- src/Summary.h
- src/commands/patch.cc
- src/commands/patch.h
- src/solve-commit.cc
- src/solve-commit.h
- src/utils/misc.cc
- src/utils/misc.h
- zypper.spec.cmake
(closes #514)
The first commits are fixes and enhancements to the patch. The last one introduces the feature.
If multiple problems are to be reported, zypper uses a 1st pass to quickly list all problems and a 2nd pass to ask to resolve each problem. 
We use the 1st pass to check for auto-applicable solutions and re-solve if solutions were applied. If problems still remain at the end, we ask.
The draft is basically ready. Remaining tasks:
> patch: add  --skip-not-applicable-patches to  autoresolve not applicable patches

- src/Summary.cc
In the zypper summary output when a package (or packages) are being added or removed, it summarises but I think this reads more clearly in this PR.
> Updating the syntax of the zypper summary for package size requirements

- doc/zypper.8.txt
- src/commands/query/info.cc
- src/info.cc
To query for a specific version simply append "-version" or "-version-release" to the "name" pattern. Note that the edition part must always match exactly.
> info: Allow to query a specific version (jsc#PED-11268)

- doc/zypper.8.txt
- src/commands/basecommand.cc
- src/commands/basecommand.h
- src/commands/distupgrade.cc
- src/commands/distupgrade.h
- src/repos.cc
(bsc#1228434, bsc#1236939, fixes#446)
> Let zypper dup fail in case of (temporarily) unaccessible repos

- doc/zypper.8.txt
- src/commands/repos/refresh.cc
- src/commands/repos/refresh.h
- zypper.spec.cmake
Future multi-arch repos may allow to download only those metadata which refer to packages actually compatible with the systems architecture. Some tools however want zypp to provide the full metadata of a repository without filtering incompatible architectures.
> refresh: add --include-all-archs (fixes #598)

- src/utils/misc.cc
[bsc#1237587](https://bugzilla.suse.com/show_bug.cgi?id=1237587)
URLs passed on the commandline must have their special chars encoded already. We just want to check and encode forgotten unsafe chars like a blank. A '%' however must not be encoded again.
Because non-Url arguments may denote a local path, the encoding check was moved into the else-part. Otherwise we may accidentally encode an  argument string which was meant to be a local pathname.
> Do not double encode URL strings passed on the commandline (bsc#1237587)
